#!/usr/bin/env bash
# Local preview of what GitHub Pages will publish.
#
# Pages runs Jekyll with the theme in docs/_config.yml. Jekyll isn't installed
# here, so this renders the same markdown with pandoc and a Cayman-like
# stylesheet. It is a PREVIEW of layout and content, not a byte-identical
# reproduction of the Pages build — treat differences in chrome as expected and
# differences in CONTENT as a bug.
#
# Output is written to preview/ which is gitignored: the published HTML must be
# generated by Pages from the markdown, not committed, or the two drift.
set -uo pipefail
cd "$(dirname "$0")"
OUT=preview
rm -rf "$OUT"; mkdir -p "$OUT"
cp -R docs/diagrams "$OUT/diagrams" 2>/dev/null

cat > "$OUT/style.css" <<'CSS'
:root { --accent:#159957; --accent2:#155799; }
body { margin:0; font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif; color:#111; }
.hdr { background:linear-gradient(120deg,var(--accent2),var(--accent)); color:#fff; padding:3rem 1rem; text-align:center; }
.hdr h1 { margin:0 0 .4rem; font-size:2.1rem; }
.hdr p { margin:0; opacity:.85; }
.nav { margin-top:1.2rem; }
.nav a { color:#fff; border:1px solid rgba(255,255,255,.5); padding:.4rem .9rem; border-radius:.3rem; text-decoration:none; margin:0 .25rem; font-size:.9rem; }
main { max-width:62rem; margin:0 auto; padding:2rem 1.25rem 4rem; }
h1,h2 { border-bottom:1px solid #eaecef; padding-bottom:.3em; margin-top:2em; }
h3 { margin-top:1.6em; }
code { background:#f6f8fa; padding:.15em .35em; border-radius:3px; font-size:.88em; }
pre { background:#f6f8fa; padding:1rem; overflow:auto; border-radius:5px; }
pre code { background:none; padding:0; }
blockquote { border-left:4px solid var(--accent); margin:1.2em 0; padding:.3em 1em; color:#444; background:#f8fdfa; }
table { border-collapse:collapse; width:100%; margin:1.2em 0; display:block; overflow-x:auto; }
th,td { border:1px solid #dfe2e5; padding:.5em .8em; text-align:left; vertical-align:top; }
th { background:#f6f8fa; }
img { max-width:100%; border:1px solid #eaecef; border-radius:4px; background:#fff; }
CSS

render() { # $1 = md file, $2 = out html, $3 = title
  # strip Jekyll front matter (portable — BSD sed chokes on the one-liner form)
  python3 - "docs/$1" "$OUT/.tmp.md" <<'STRIP'
import sys, pathlib
src, dst = sys.argv[1], sys.argv[2]
lines = pathlib.Path(src).read_text().split('\n')
if lines and lines[0].strip() == '---':
    end = next((i for i, l in enumerate(lines[1:], 1) if l.strip() == '---'), 0)
    lines = lines[end + 1:]
pathlib.Path(dst).write_text('\n'.join(lines))
STRIP
  pandoc "$OUT/.tmp.md" -f gfm -t html5 --standalone --metadata title="$3" \
    --css style.css \
    --include-before-body=<(cat <<HTML
<div class="hdr"><h1>$3</h1><p>Brokered credential access across an inspecting boundary</p>
<div class="nav"><a href="index.html">Overview</a><a href="credential-broker-pattern.html">The pattern</a><a href="gateway-evaluation.html">Gateway evaluation</a></div></div><main>
HTML
) --include-after-body=<(echo "</main>") -o "$OUT/$2" 2>/dev/null \
  && echo "  rendered $2" || echo "  FAILED $2"
}

strip_title() { python3 - "$1" <<'S'
import re, sys, pathlib
p = pathlib.Path(sys.argv[1]); t = p.read_text()
p.write_text(re.sub(r'<h1 class="title">.*?</h1>\s*', '', t, flags=re.S))
S
}

render index.md                     index.html                     "Overview"
render credential-broker-pattern.md credential-broker-pattern.html "The Credential Broker Pattern"
render gateway-evaluation.md        gateway-evaluation.html        "Gateway evaluation"
for h in "$OUT"/*.html; do strip_title "$h"; done
rm -f "$OUT/.tmp.md"
echo "  open: file://$(pwd)/$OUT/index.html"
